'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace CarsModelService


    Partial Public Class SiteMaster

        ''' <summary>
        ''' HeadContent control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        ''' <summary>
        ''' MasterPageScriptManager control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MasterPageScriptManager As Global.System.Web.UI.ScriptManager

        ''' <summary>
        ''' HeadLoginView control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected HeadLoginView As Global.System.Web.UI.WebControls.LoginView

        ''' <summary>
        ''' HeadHomeLink control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected HeadHomeLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

        ''' <summary>
        ''' HeadAboutLink control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected HeadAboutLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

        ''' <summary>
        ''' MainContent control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
