//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 6/25/2013 16:33:14
namespace WpfApplication1.CarsModelService1
{
    
    /// <summary>
    /// There are no comments for CarsModelEntities in the schema.
    /// </summary>
    public partial class CarsModelEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new CarsModelEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CarsModelEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("CarsModelModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WpfApplication1.CarsModelService1", typeName.Substring(14)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WpfApplication1.CarsModelService1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CarsModelModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Cars in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Car> Cars
        {
            get
            {
                if ((this._Cars == null))
                {
                    this._Cars = base.CreateQuery<Car>("Cars");
                }
                return this._Cars;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Car> _Cars;
        /// <summary>
        /// There are no comments for CarSchedulings in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CarScheduling> CarSchedulings
        {
            get
            {
                if ((this._CarSchedulings == null))
                {
                    this._CarSchedulings = base.CreateQuery<CarScheduling>("CarSchedulings");
                }
                return this._CarSchedulings;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CarScheduling> _CarSchedulings;
        /// <summary>
        /// There are no comments for Cars in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCars(Car car)
        {
            base.AddObject("Cars", car);
        }
        /// <summary>
        /// There are no comments for CarSchedulings in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCarSchedulings(CarScheduling carScheduling)
        {
            base.AddObject("CarSchedulings", carScheduling);
        }
    }
    /// <summary>
    /// There are no comments for CarsModelModel.Car in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Cars")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Car : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Car object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Car CreateCar(int ID)
        {
            Car car = new Car();
            car.ID = ID;
            return car;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Trademark in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Trademark
        {
            get
            {
                return this._Trademark;
            }
            set
            {
                this.OnTrademarkChanging(value);
                this._Trademark = value;
                this.OnTrademarkChanged();
                this.OnPropertyChanged("Trademark");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Trademark;
        partial void OnTrademarkChanging(string value);
        partial void OnTrademarkChanged();
        /// <summary>
        /// There are no comments for Property Model in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Model
        {
            get
            {
                return this._Model;
            }
            set
            {
                this.OnModelChanging(value);
                this._Model = value;
                this.OnModelChanged();
                this.OnPropertyChanged("Model");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Model;
        partial void OnModelChanging(string value);
        partial void OnModelChanged();
        /// <summary>
        /// There are no comments for Property HP in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> HP
        {
            get
            {
                return this._HP;
            }
            set
            {
                this.OnHPChanging(value);
                this._HP = value;
                this.OnHPChanged();
                this.OnPropertyChanged("HP");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _HP;
        partial void OnHPChanging(global::System.Nullable<short> value);
        partial void OnHPChanged();
        /// <summary>
        /// There are no comments for Property Liter in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> Liter
        {
            get
            {
                return this._Liter;
            }
            set
            {
                this.OnLiterChanging(value);
                this._Liter = value;
                this.OnLiterChanged();
                this.OnPropertyChanged("Liter");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _Liter;
        partial void OnLiterChanging(global::System.Nullable<double> value);
        partial void OnLiterChanged();
        /// <summary>
        /// There are no comments for Property Cyl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> Cyl
        {
            get
            {
                return this._Cyl;
            }
            set
            {
                this.OnCylChanging(value);
                this._Cyl = value;
                this.OnCylChanged();
                this.OnPropertyChanged("Cyl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _Cyl;
        partial void OnCylChanging(global::System.Nullable<byte> value);
        partial void OnCylChanged();
        /// <summary>
        /// There are no comments for Property TransmissSpeedCount in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> TransmissSpeedCount
        {
            get
            {
                return this._TransmissSpeedCount;
            }
            set
            {
                this.OnTransmissSpeedCountChanging(value);
                this._TransmissSpeedCount = value;
                this.OnTransmissSpeedCountChanged();
                this.OnPropertyChanged("TransmissSpeedCount");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _TransmissSpeedCount;
        partial void OnTransmissSpeedCountChanging(global::System.Nullable<byte> value);
        partial void OnTransmissSpeedCountChanged();
        /// <summary>
        /// There are no comments for Property TransmissAutomatic in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TransmissAutomatic
        {
            get
            {
                return this._TransmissAutomatic;
            }
            set
            {
                this.OnTransmissAutomaticChanging(value);
                this._TransmissAutomatic = value;
                this.OnTransmissAutomaticChanged();
                this.OnPropertyChanged("TransmissAutomatic");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TransmissAutomatic;
        partial void OnTransmissAutomaticChanging(string value);
        partial void OnTransmissAutomaticChanged();
        /// <summary>
        /// There are no comments for Property MPG_City in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> MPG_City
        {
            get
            {
                return this._MPG_City;
            }
            set
            {
                this.OnMPG_CityChanging(value);
                this._MPG_City = value;
                this.OnMPG_CityChanged();
                this.OnPropertyChanged("MPG_City");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _MPG_City;
        partial void OnMPG_CityChanging(global::System.Nullable<byte> value);
        partial void OnMPG_CityChanged();
        /// <summary>
        /// There are no comments for Property MPG_Highway in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<byte> MPG_Highway
        {
            get
            {
                return this._MPG_Highway;
            }
            set
            {
                this.OnMPG_HighwayChanging(value);
                this._MPG_Highway = value;
                this.OnMPG_HighwayChanged();
                this.OnPropertyChanged("MPG_Highway");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<byte> _MPG_Highway;
        partial void OnMPG_HighwayChanging(global::System.Nullable<byte> value);
        partial void OnMPG_HighwayChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Hyperlink in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Hyperlink
        {
            get
            {
                return this._Hyperlink;
            }
            set
            {
                this.OnHyperlinkChanging(value);
                this._Hyperlink = value;
                this.OnHyperlinkChanged();
                this.OnPropertyChanged("Hyperlink");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Hyperlink;
        partial void OnHyperlinkChanging(string value);
        partial void OnHyperlinkChanged();
        /// <summary>
        /// There are no comments for Property Picture in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Picture
        {
            get
            {
                if ((this._Picture != null))
                {
                    return ((byte[])(this._Picture.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPictureChanging(value);
                this._Picture = value;
                this.OnPictureChanged();
                this.OnPropertyChanged("Picture");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Picture;
        partial void OnPictureChanging(byte[] value);
        partial void OnPictureChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Price;
        partial void OnPriceChanging(global::System.Nullable<decimal> value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property RtfContent in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RtfContent
        {
            get
            {
                return this._RtfContent;
            }
            set
            {
                this.OnRtfContentChanging(value);
                this._RtfContent = value;
                this.OnRtfContentChanged();
                this.OnPropertyChanged("RtfContent");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RtfContent;
        partial void OnRtfContentChanging(string value);
        partial void OnRtfContentChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CarsModelModel.CarScheduling in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CarSchedulings")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class CarScheduling : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CarScheduling object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="allDay">Initial value of AllDay.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CarScheduling CreateCarScheduling(int ID, bool allDay)
        {
            CarScheduling carScheduling = new CarScheduling();
            carScheduling.ID = ID;
            carScheduling.AllDay = allDay;
            return carScheduling;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property CarId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> CarId
        {
            get
            {
                return this._CarId;
            }
            set
            {
                this.OnCarIdChanging(value);
                this._CarId = value;
                this.OnCarIdChanged();
                this.OnPropertyChanged("CarId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _CarId;
        partial void OnCarIdChanging(global::System.Nullable<int> value);
        partial void OnCarIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _UserId;
        partial void OnUserIdChanging(global::System.Nullable<int> value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Status;
        partial void OnStatusChanging(global::System.Nullable<int> value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Subject in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this._Subject = value;
                this.OnSubjectChanged();
                this.OnPropertyChanged("Subject");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Label in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Label
        {
            get
            {
                return this._Label;
            }
            set
            {
                this.OnLabelChanging(value);
                this._Label = value;
                this.OnLabelChanged();
                this.OnPropertyChanged("Label");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Label;
        partial void OnLabelChanging(global::System.Nullable<int> value);
        partial void OnLabelChanged();
        /// <summary>
        /// There are no comments for Property StartTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return this._StartTime;
            }
            set
            {
                this.OnStartTimeChanging(value);
                this._StartTime = value;
                this.OnStartTimeChanged();
                this.OnPropertyChanged("StartTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
        /// <summary>
        /// There are no comments for Property EndTime in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return this._EndTime;
            }
            set
            {
                this.OnEndTimeChanging(value);
                this._EndTime = value;
                this.OnEndTimeChanged();
                this.OnPropertyChanged("EndTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property AllDay in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool AllDay
        {
            get
            {
                return this._AllDay;
            }
            set
            {
                this.OnAllDayChanging(value);
                this._AllDay = value;
                this.OnAllDayChanged();
                this.OnPropertyChanged("AllDay");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _AllDay;
        partial void OnAllDayChanging(bool value);
        partial void OnAllDayChanged();
        /// <summary>
        /// There are no comments for Property EventType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> EventType
        {
            get
            {
                return this._EventType;
            }
            set
            {
                this.OnEventTypeChanging(value);
                this._EventType = value;
                this.OnEventTypeChanged();
                this.OnPropertyChanged("EventType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _EventType;
        partial void OnEventTypeChanging(global::System.Nullable<int> value);
        partial void OnEventTypeChanged();
        /// <summary>
        /// There are no comments for Property RecurrenceInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RecurrenceInfo
        {
            get
            {
                return this._RecurrenceInfo;
            }
            set
            {
                this.OnRecurrenceInfoChanging(value);
                this._RecurrenceInfo = value;
                this.OnRecurrenceInfoChanged();
                this.OnPropertyChanged("RecurrenceInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RecurrenceInfo;
        partial void OnRecurrenceInfoChanging(string value);
        partial void OnRecurrenceInfoChanged();
        /// <summary>
        /// There are no comments for Property ReminderInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ReminderInfo
        {
            get
            {
                return this._ReminderInfo;
            }
            set
            {
                this.OnReminderInfoChanging(value);
                this._ReminderInfo = value;
                this.OnReminderInfoChanged();
                this.OnPropertyChanged("ReminderInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ReminderInfo;
        partial void OnReminderInfoChanging(string value);
        partial void OnReminderInfoChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Price;
        partial void OnPriceChanging(global::System.Nullable<decimal> value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property ContactInfo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContactInfo
        {
            get
            {
                return this._ContactInfo;
            }
            set
            {
                this.OnContactInfoChanging(value);
                this._ContactInfo = value;
                this.OnContactInfoChanged();
                this.OnPropertyChanged("ContactInfo");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContactInfo;
        partial void OnContactInfoChanging(string value);
        partial void OnContactInfoChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
